---
- hosts: node03
  become: yes
  tasks:

    - name: Create document root directories node03
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /var/www/red_server
        - /var/www/green_server

    - name: Copy websites to node03
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: "~/ansible-path/Websites/red.html", dest: "/var/www/red_server/index.html" }
        - { src: "~/ansible-path/Websites/green.html", dest: "/var/www/green_server/index.html" }

    - name: Copy virtual host configs to node03
      ansible.builtin.template:
        src: ~/ansible-path/Templates/vhost_template.conf.j2
        dest: "/etc/apache2/sites-available/{{ item.name }}_site.conf"
      loop:
        - { name: "red", port: "1111", document_root: "/var/www/red_server" }
        - { name: "green", port: "2222", document_root: "/var/www/green_server" }

    - name: Enable virtual host configs on node03
      ansible.builtin.command: "a2ensite {{ item.name }}_site.conf"
      loop:
        - { name: "red" }
        - { name: "green" }

    - name: Restart Apache2 service
      ansible.builtin.service:
        name: apache2
        state: restarted
