---

- hosts: all
  become: true
  tasks:

  - name: Updating repository index. Install apache2 & php packages
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
